apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-depl
spec:
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: tikzsz/payment
        ports:
        - containerPort: 3000
        env:
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
                
          - name: MONGO_URI
            value: mongodb://payment-mongo-srv:27017/payments

          - name: NATS_CLUSTER_ID
            value: 'ticketing'

          - name: 'NATS_URL'
            value: 'http://nats-srv:4222'

          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: payment-srv
spec:
  selector:
    app: payment
  ports:
  - port: 3000
    targetPort: 3000
